
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and publish Docker image
      run: |
        dotnet publish -c Release
        docker build -f Dockerfile -t discord_bot_garrisson:latest .
        docker tag discord_bot_garrisson:latest ${{secrets.DOCKER_USERNAME}}/discord_bot_garrisson:latest
        docker push ${{secrets.DOCKER_USERNAME}}/discord_bot_garrisson:latest
